services:
  server:
    build: .
    restart: always
    ports: 
      - 25565:25565
      - 25575:25575
    volumes:
      - "minecraft-server:/data:rw"
    stdin_open: true
    tty: true

volumes:
  minecraft-server:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/minecraft'