services:
  minecraft:
    build: .
    restart: always
    depends_on:
      - mariadb
    networks: 
      - all
    ports: 
        #mc
      - 25565:25565
        #rcon
      - 25575:25575
        #simple voice chat
      - 25545:25545
    volumes:
      - "minecraft-server:/data:rw"
    stdin_open: true
    tty: true

  mariadb:
    networks: 
      - all
    image: mariadb
    restart: always
    volumes: 
      - "database-server:/var/lib/mysql:rw"
    env_file: .env

volumes:
  minecraft-server:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/minecraft'
  database-server:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/database'

networks:
  all: